name: Generate Report

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'TestRail Project ID'
        required: true
        type: number
      plan:
        description: 'TestRail Plan ID (optional if using run)'
        required: false
        type: number
      run:
        description: 'TestRail Run ID (optional if using plan)'
        required: false
        type: number

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build CLI arguments
        id: build_args
        shell: bash
        run: |
          set -euo pipefail
          ARGS=("--project" "${{ github.event.inputs.project }}")
          if [ -n "${{ github.event.inputs.plan }}" ]; then
            ARGS+=("--plan" "${{ github.event.inputs.plan }}")
          fi
          if [ -n "${{ github.event.inputs.run }}" ]; then
            ARGS+=("--run" "${{ github.event.inputs.run }}")
          fi
          printf 'args=%q ' "${ARGS[@]}" | sed 's/ $//' >> "$GITHUB_OUTPUT"

      - name: Generate report
        env:
          TESTRAIL_BASE_URL: ${{ secrets.TESTRAIL_BASE_URL }}
          TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
          TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
        run: |
          python testrail_daily_report.py ${{ steps.build_args.outputs.args }}

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: testrail-report
          path: out/*.html
          if-no-files-found: error

